app:
    build: app
    links:
      - "db:redis"
haproxy:
    image: tutum/haproxy
    ports:
      - "80:80"
      - "1936:1936"
    links:
        - app
    environment:
        - BACKEND_PORT=8080
db:
  image: redis
  ports:
    - "6379:6379"
